name: logicat-iot
title: Logicatsrl IoT Gateway
base: core18 # the base snap is the execution environment for this snap
architectures:
  - build-on: amd64
    run-on:  amd64
  - build-on: armhf
    run-on: armhf
version: '0.1.0'
summary: Logicatsrl IoT gateway, drive the data to the GCP infrasctucture. # 79 char long summary
description: |
  (Private snap actually in beta version) This is the Logicat srl IoT 
  gateway, the only feature is to drive the data from field to GCP, in 
  the local network the data are gather with TCP socket connections, on
  gateway data are processed and ingested into GCP with Pub/Sub message 
  architecture. Device stauts data and field data can be handled with 
  different accounts and security flow. 

type: app
icon: logicat.png
license: ISC
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  node-service:
    command: logicat-iot  # same as (bin/chuck-norris-app) referencing starting binary generated by package.json
    # daemon: simple
    # restart-condition: always
    plugs: [home,network,network-bind]

parts:
  node-service:
    source: .
    plugin: nodejs
    nodejs-version: "13.11.0"
    nodejs-package-manager: "yarn"
    nodejs-yarn-version: "v1.22.4"
