name: logicat-iot
title: Logicatsrl IoT Gateway
base: core18
architectures:
  - build-on: amd64
    run-on:  amd64
  - build-on: armhf
    run-on: armhf
version: '1.4.0'
summary: Logicatsrl IoT gateway, drive the data to the GCP infrasctucture. # 79 char long summary
description: |
  (Private snap actually in beta version) This is the Logicat srl IoT 
  gateway, the only feature is to drive the data from field to GCP, in 
  the local network the data are gather with TCP socket connections, on
  gateway data are processed and ingested into GCP with Pub/Sub message 
  architecture. Device stauts data and field data can be handled with 
  different accounts and security flow. 

type: app
icon: logicat.png
license: ISC
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  # node logicat-iot service 
  node-service:
    command: logicat-iot 
    daemon: simple
    restart-condition: always
    restart-delay: 10s
    plugs: [network,network-bind]
  # redis service 
  redis-server:
    command: redis-server $SNAP/config/redis/redis.conf
    daemon: simple
    plugs: [network, network-bind]
  redis-benchmark:
    command: redis-benchmark
    plugs: [network]
  redis-check-aof:
    command: redis-check-aof
  redis-check-rdb:
    command: redis-check-rdb
  redis-cli:
    command: redis-cli
    plugs: [network]
  redis-sentinel:
    command: redis-sentinel
    plugs: [network, network-bind]

parts:
  # node.js logicat-iot code 
  node-service:
    source: .
    plugin: nodejs
    nodejs-version: "14.13.0"
    nodejs-package-manager: "npm"
    stage-packages:
      - libatomic1
  # building redis 
  redis:
    plugin: make
    source: https://github.com/antirez/redis.git
    source-tag: '6.0.5'
    build-packages:
      - build-essential
    make-install-var: 'PREFIX'
  # set the custom redis configuration 
  redis-customizations:
    plugin: dump
    source: redis/
    organize:
      config/*: config/redis/
